{% set version = "0.6.1" %}

package:
  name: lasy
  version: {{ version }}

source:
  url: https://github.com/LASY-org/lasy/archive/refs/tags/{{ version }}.tar.gz
  sha256: 52345a8cc82a636974f06e3c5543f6d173ebe3942ff0034d119c43782c23bc94

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - axiprop
    - numpy
    - openpmd-api
    - openpmd-viewer
    - python >={{ python_min }}
    - scipy

test:
  requires:
    - matplotlib
    - python {{ python_min }}
    - pytest
    - scikit-image
  source_files:
    - examples/
    - tests/
  imports:
    - lasy

about:
  home: https://lasydoc.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  summary: "A Python library that facilitates the initialization of complex laser pulses in simulations."

  description: |
    lasy offers many ways to define complex laser pulses (e.g. from
    commonly-known analytical formulas, from experimental measurements, etc.)
    and offers pre-processing functionalities (e.g. propagation,
    re-normalization, geometry conversion). The laser field is then exported in
    a standardized file, that can be read by external simulation codes.
  dev_url: https://github.com/LASY-org/lasy

extra:
  recipe-maintainers:
    - AngelFP
    - ax3l
    - hightower8083
    - MaxThevenet
    - RemiLehe
    - rob-shalloo
