{% set version = "0.4.0" %}

package:
  name: lasy
  version: {{ version }}

source:
  url: https://github.com/LASY-org/lasy/archive/refs/tags/{{ version }}.tar.gz
  sha256: 83992dee8146036ba4eb4a97621e1dbdcb857c11b8901b2769a67bb81636015d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - axiprop
    - numpy
    - openpmd-api
    - openpmd-viewer
    - python >=3.7
    - scipy

test:
  requires:
    - python
    - pytest
  source_files:
    - examples/
    - tests/
  imports:
    - lasy

about:
  home: https://lasydoc.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  summary: "A Python library that facilitates the initialization of complex laser pulses in simulations."

  description: |
    lasy offers many ways to define complex laser pulses (e.g. from
    commonly-known analytical formulas, from experimental measurements, etc.)
    and offers pre-processing functionalities (e.g. propagation,
    re-normalization, geometry conversion). The laser field is then exported in
    a standardized file, that can be read by external simulation codes.
  dev_url: https://github.com/LASY-org/lasy

extra:
  recipe-maintainers:
    - AngelFP
    - ax3l
    - hightower8083
    - MaxThevenet
    - RemiLehe
    - rob-shalloo
